### ISSUE TITLE
Towards a simpler approach to validate()

### ISSUE THREAD

**Issue by lucasmreis** [jsanchesleao/enforcement#1]
First of all, thanks for the amazing library! :)

So, I'm thinking in a simpler approach to your validate() function. Instead of instantiating an object, setting up new constraints, setting up the schema, and then calling the function on different objetcs, I propose something along the lines:

```
validate = function(constraints, schema, objectToBeTested);
```

The function would also be curried, so one could achieve similar results of "setting up", but the function would still be pure and simple:

```
var constraints = [ ...new constraints we would like to have... ];

var validationConstraints = validate(constraints);

var validateUser = validationConstraints({ ...schema for "User" object... });

// finally one could validate User objects with the validateUser function:
var validatedUser = validateUser(someObject);
```

The problems this approach tries to solve are mainly _control problems_, which are problems related to the order things happen in the code. With the curried function, the first parameter is _always_ the constraints array, and it _always_ happen before the schema definition, which _always_ happen before the validation. So, there's no room for a situation like "oh, I registered that constraint after doing the validations!".

The only problem I see would be the schema syntax for a nested object.

What do you think? If you agree, I'll make the pull request and start working on this solution!

Thank you one more time,
Lucas

**Comment by jsanchesleao** [comment]
Actually I found this approach pretty interesting, and would like to move to a more functional and simpler API.
It's a great candidate for a next release. Thanks for the collab. (Pull requests are most appreciated :D)
