### ISSUE TITLE
Mocha error

### ISSUE THREAD

**Issue by raine** [jsanchesleao/enforcement#2]
In my mocha test I have a promise that is rejected with an error produced by enforcement.

This is what happens:

```
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at node_modules/mocha/lib/utils.js:722:18
```

After that mocha watcher dies.

Line 722 in that file is this:

```
stack = stack.split('\n');
```

So I tried adding `this.stack = '';` to `validationError.js` and that fixed it. There must be something wrong with this line in `validationError.js` that is supposed to get a stack trace:

```
Error.captureStackTrace(this, this.constructor); //super helper method to include stack trace in error object
```

**Comment by jsanchesleao** [comment]
There seems to be a problem with that custom error object. 

By tomorrow I'll patch it with your solution.

Anyway I'm thinking about removing that and stick with a regular Error. What do you think?

**Comment by jsanchesleao** [comment]
I mean, removing the custom error

**Comment by raine** [comment]
Works for me. Perhaps https://www.npmjs.com/package/error?

Sent from my iPhone

## 

Raine

**Comment by jsanchesleao** [comment]
Nice, that should do the trick. Thanks :)

**Comment by jsanchesleao** [comment]
0.0.8 is there with that hotfix. Later I'll try https://www.npmjs.com/package/error, and check if this will break any existing code.

**Comment by raine** [comment]
Thanks!
