### ISSUE TITLE
Issue with Object.freeze(this) in validationError.js

### ISSUE THREAD

**Issue by raine** [jsanchesleao/enforcement#3]
I'm using [`error-create`](https://github.com/medikoo/error-create) to wrap errors produced by `enforcement` and I noticed that if I include [`error-callsites`](https://www.npmjs.com/package/error-callsites) module anywhere in the project I start getting a weird error:

```
node_modules/error-create/abstract.js:23
        if (ext != null) assign(this, ext);
                         ^

TypeError: Cannot define property:__error_callsites, object is not extensible.
    at Function.defineProperty (native)
    at Function.Error.prepareStackTrace (node_modules/error-callsites/index.js:7:10)
    at assign (native)
    at AbstractError (node_modules/error-create/abstract.js:23:19)
    at new CustomError (node_modules/error-create/index.js:21:17)
    at CustomError (node_modules/error-create/index.js:19:23)
```

Some debugging and I notice it's only related to errors produced by enforcement and I also discover that by commenting [this line](https://github.com/jsanchesleao/enforcement/blob/4c20d043aca568037bdc8f49b2c17962238c269e/lib/validationError.js#L13) in `validationError.js` the error goes away. Is there a good reason to do the `Object.freeze`?

``` js
require('error-callsites') // error won't happen without this

var validator = require('enforcement').create()
var createError = require('error-create')
var SomeValidationError = createError('SomeValidationError')

var Person = validator.Schema({
  name: 'string',
  age: 'number'
})

try {
  Person.check({
    name: 'jeff',
    age: 'BAD'
  })
} catch(err) {
  var wrappedErr = SomeValidationError(err.message, err)
}
```

**Comment by jsanchesleao** [comment]
In fact there was no major reason to use Object.freeze, it was there only to assure the consistency of the error object. I removed it in 0.0.9 because of the problems you told. Also there seems to be a performance issue with Object.freeze, so I think it's gone for good :)

Thanks for the feedback
